CREATE TABLE MOVIE (
ID NUMBER,
CONSTRAINT const_id1 PRIMARY KEY(ID),
TITLE NVARCHAR2(50) NOT NULL UNIQUE,
DIRECTOR NVARCHAR2 (20) NOT NULL,
YEAR NUMBER CHECK ((1900<YEAR) AND (YEAR<2020)),
LENGHT_MINS NUMBER CHECK ((10<LENGHT_MINS) AND (LENGHT_MINS<200))
);