CREATE TABLE HOTEL (
ID NUMBER,
 CONSTRAINT AUTHOR_PK PRIMARY KEY(ID),
 COUNTRY NVARCHAR2(50) DEFAULT 'N/A',
 CONSTRAINT CHECK_COUNTRY CHECK(COUNTRY !='Romaniy' OR COUNTRY !='Belgium' OR COUNTRY !='China' OR COUNTRY !='Romaniy' ),
 SITY NVARCHAR2(50) NOT NULL,
 STREET NVARCHAR2
)